global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ML Service
  - job_name: 'ml-service'
    static_configs:
      - targets: ['ml-service:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Web Frontend
  - job_name: 'web-frontend'
    static_configs:
      - targets: ['web-frontend:80']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis (if using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
